server:
  port: 1111
spring:
  datasource:
    url: jdbc:h2:mem:onboard2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  profiles:
    include: env
  jpa:
    defer-datasource-initialization: false
    show-sql: false
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop #for h2
#      ddl-auto: validate #for mariadb
      type: trace
logging:
  level:
    p6spy: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN